package com.a9ae0b01f0ffc.commons.main

import com.a9ae0b01f0ffc.commons.config_helper.T_conf

class T_common_commons {

    T_conf GC_CONST_CONF = T_common_const.GC_NULL_OBJ_REF as T_conf
    String GC_DATETIMESTAMP_FORMAT = "yyyy-MM-dd HH:mm:ss:SSS"
    String GC_FILENAME_DATE_FORMAT = "yyyyMMdd"
    String GC_FILENAME_TIME_FORMAT = "HHmmssSSS"
    String GC_CLASS_LOADER_CONF_FILE_NAME = T_common_const.GC_EMPTY_STRING
    String GC_MESSAGE_FORMAT_TOKEN_SEPARATOR_BEFORE = "_"
    String GC_MESSAGE_FORMAT_TOKEN_SEPARATOR_AFTER = " "
    String GC_MESSAGE_FORMAT_TOKEN_TRACE = "Z"
    String GC_SUBST_USERNAME = "%USERNAME%"
    String GC_SUBST_DATE = "%DATE%"
    String GC_SUBST_TIME = "%TIME%"
    String GC_SUBST_THREADID = "%THREADID%"
    String GC_SUBST_PROCESSID = "%PROCESSID%"
    String GC_THREADID = Long.toString(Thread.currentThread().getId())

    T_common_commons(String i_conf_file_name) {
        GC_CONST_CONF = new T_conf(i_conf_file_name)
        GC_DATETIMESTAMP_FORMAT = GC_CONST_CONF.GC_LOG_DATETIMESTAMP_FORMAT(GC_DATETIMESTAMP_FORMAT)
        GC_FILENAME_DATE_FORMAT = GC_CONST_CONF.GC_LOG_FILENAME_DATE_FORMAT(GC_FILENAME_DATE_FORMAT)
        GC_FILENAME_TIME_FORMAT = GC_CONST_CONF.GC_LOG_FILENAME_TIME_FORMAT(GC_FILENAME_TIME_FORMAT)
        GC_CLASS_LOADER_CONF_FILE_NAME = GC_CONST_CONF.GC_CLASS_LOADER_CONF_FILE_NAME(GC_CLASS_LOADER_CONF_FILE_NAME)
        GC_MESSAGE_FORMAT_TOKEN_SEPARATOR_BEFORE = GC_CONST_CONF.GC_MESSAGE_FORMAT_TOKEN_SEPARATOR_BEFORE(GC_MESSAGE_FORMAT_TOKEN_SEPARATOR_BEFORE)
        GC_MESSAGE_FORMAT_TOKEN_SEPARATOR_AFTER = GC_CONST_CONF.GC_MESSAGE_FORMAT_TOKEN_SEPARATOR_AFTER(GC_MESSAGE_FORMAT_TOKEN_SEPARATOR_AFTER)
        GC_MESSAGE_FORMAT_TOKEN_TRACE = GC_CONST_CONF.GC_MESSAGE_FORMAT_TOKEN_TRACE(GC_MESSAGE_FORMAT_TOKEN_TRACE)
        GC_SUBST_USERNAME = GC_CONST_CONF.GC_SUBST_USERNAME(GC_SUBST_USERNAME)
        GC_SUBST_DATE = GC_CONST_CONF.GC_SUBST_DATE(GC_SUBST_DATE)
        GC_SUBST_TIME = GC_CONST_CONF.GC_SUBST_TIME(GC_SUBST_TIME)
        GC_SUBST_THREADID = GC_CONST_CONF.GC_SUBST_THREADID(GC_SUBST_THREADID)
        GC_SUBST_PROCESSID = GC_CONST_CONF.GC_SUBST_PROCESSID(GC_SUBST_PROCESSID)
    }
}
